parsons-tool-frontend/src/components/Login.js
parsons-tool-frontend/src/data/AuthContext.js
parsons-tool-frontend/src/data/ProblemContext.js
parsons-tool-frontend/src/hooks/useGet.js
parsons-tool-frontend/src/pages/Introduction.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js

- login now relies on auth context finding a record, rather than firebase; this should help reduce the issue where people could log in in but no record was created in the backend, and thus no problems were added.
- Added some more consoles when in an error state to help and try to diagnose the problem quickly.
- Removed some unneeded console logs

Change how login is done

---

parsons-tool-frontend/src/components/parsonsProblem.js

- use dnd-kit mouseSensor to prevent drag event overriding text input focus (I believe this was the problem)
#58

add in mouse sensor

---

parsons-tool-frontend/src/data/BackendContext.js
parsons-tool-frontend/src/hooks/usePost.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js

- add in a clear method for clearing the response data of a post request
- call this after a submission to remove the state before the next problem

add in a clear state for execution response

---

parsons-tool-frontend/src/components/space/Space.js

- helps make it seem a bit clean if there are more blocks than the space can provide, a scrollbar will appear

add an overflow for the spaces

---

parsons-tool-frontend/src/pages/Summary.js

- Changed form to use email instead
- removed the group number from the code

Remove group number from form

---

parsons-tool-backend/src/routes/api/solve.js
parsons-tool-frontend/src/components/testCases/ResultComponent.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js

- added a new component for execution results
- fixed up backend to return results

Implement FE rendering of new execution results format

---

parsons-tool-frontend/src/pages/ProblemEvaluation.js

- uses callback function to trigger the creation of a logSubmission event after the results from execution get back

Adding in submission event call

---

parsons-tool-frontend/src/pages/ProblemEvaluation.js

Re-labelled, re-coloured, re-positioned buttons

---

parsons-tool-frontend/src/pages/ProblemEvaluation.js

changes from result console to a better name

---

parsons-tool-frontend/src/components/blocks/Block.js

slightly buggy, if you hold down a key it may not capture the length quite correctly, but it tends to work as long as you type in carefully.
Also sometimes breaks (doesn't capture length properly) if you type from earlier in the string

temporary fix for increasing width of inputs

---

parsons-tool-frontend/src/pages/Summary.js

 Move form into iframe on page

---

parsons-tool-backend/src/database/DataLogSchema.js
parsons-tool-frontend/src/components/space/Space.js
parsons-tool-frontend/src/loggers/logContext.js
parsons-tool-frontend/src/loggers/logExecution.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js

- laptop spacing still brought up the overflow; this helps prevent the overflow from showing up on the laptop screen
- added in test execution results to the data log
- Major issue still present, is that logs don't showcase the latest log, so if you submit the submission log is not shown

Fixed height spacing of boxes + added in execution logs

---

parsons-tool-backend/src/database/DataLogSchema.js
parsons-tool-backend/src/routes/api/solve.js
parsons-tool-frontend/src/components/space/Space.js
parsons-tool-frontend/src/hooks/usePost.js
parsons-tool-frontend/src/loggers/logContext.js
parsons-tool-frontend/src/loggers/logExecution.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js

Test exception errors

---

parsons-tool-backend/src/routes/api/data.js
parsons-tool-backend/src/routes/api/solve.js
parsons-tool-backend/src/routes/api/student.js
parsons-tool-backend/src/routes/index.js
parsons-tool-frontend/package.json
parsons-tool-frontend/src/App.js
parsons-tool-frontend/src/components/DataLogObject.js
parsons-tool-frontend/src/components/analytics/AverageTimeGraph.js
parsons-tool-frontend/src/components/analytics/DataLogObject.js
parsons-tool-frontend/src/data/BackendContext.js
parsons-tool-frontend/src/pages/DataAnalytics.js
parsons-tool-frontend/src/pages/PageLayout.js
yarn.lock

Created a data page with some graphics and tables that can be interacted with to show all datalogs in the database
Table showing experiment + graph of all datalogs avg time + num of datalogs
Graphs for each question type, comparing experiment groups
Table showing more details on each datalog (click on a particular data log to bring up detailed view)
Highlights errors/incorrect test cases

Data Visualisation

---

parsons-tool-frontend/src/components/parsonsProblem.js
parsons-tool-frontend/src/data/ProblemContext.js
parsons-tool-frontend/src/pages/Introduction.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js
parsons-tool-frontend/src/pages/Summary.js

- removed the intermediate page which was used between questions
- removed unused code after this was removed
- refactored how the evaluation page loads problems
- refactored how the parsons problem loads problems

Remove intermediate page

---

parsons-tool-frontend/src/components/blocks/Block.js
parsons-tool-frontend/src/components/parsonsProblem.js
parsons-tool-frontend/src/components/space/Space.js

Bug is caused by our custom indentation code overwriting the y transforms provided by dnd-kit.
Merge #113 before merging this in

Fix indented y swap transition

---

parsons-tool-frontend/src/pages/Introduction.js

-updated numbers to be accurate 
-removed incorrect instruction

Fix intro description

---

parsons-tool-frontend/src/pages/ProblemEvaluation.js

Add in prompt to remind students to fill in faded blocks

---

parsons-tool-backend/docker-compose.yml
parsons-tool-backend/src/middleware/auth.js
parsons-tool-backend/src/routes/api/student.js
parsons-tool-frontend/package.json
parsons-tool-frontend/public/index.html
parsons-tool-frontend/src/components/Modal.js
parsons-tool-frontend/src/data/BackendContext.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js
parsons-tool-frontend/tailwind.config.js
yarn.lock

Merge in #126 before merging this in

Add modals

---

parsons-tool-frontend/src/pages/Summary.js

- increased font size
- changed message slightly to include a message about marks
- increases the height of the survey
signout button is still beneath the page, but survey takes as much space as possible now

Updated survey

---

parsons-tool-backend/docker-compose.yml
parsons-tool-backend/src/middleware/auth.js
parsons-tool-backend/src/routes/api/data.js
parsons-tool-backend/src/routes/api/student.js
parsons-tool-frontend/package.json
parsons-tool-frontend/public/index.html
parsons-tool-frontend/src/components/Modal.js
parsons-tool-frontend/src/data/BackendContext.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js
parsons-tool-frontend/tailwind.config.js
yarn.lock

Merge #127 before merging this PR in.
~~Right now there is no screen for when the student has completed all problems and tries to do it again.~~

Track progress

---

parsons-tool-backend/src/routes/api/student.js
parsons-tool-frontend/src/components/Login.js
parsons-tool-frontend/src/components/Modal.js
parsons-tool-frontend/src/data/AuthContext.js
parsons-tool-frontend/src/data/BackendContext.js
parsons-tool-frontend/src/firebase.js
parsons-tool-frontend/src/pages/Introduction.js
parsons-tool-frontend/src/pages/ProblemEvaluation.js
parsons-tool-frontend/src/pages/Summary.js

- Added in check to backend before user creation for the email address domain. It responds with an error if the domain is not a UoA one.
- Added in modal display to the frontend to render the error if the domain is incorrect
- Added in modal display to login if there is another error
- Slightly changed modal styling to have buttons aligned evenly + with no border to be more consistent with our front end
- added in an email display for the top right where it says quit

Fixed Domain + Modal styling + email display

---

parsons-tool-frontend/public/index.html

- if you are happy with the title change, feel free to merge after reviewing

change title
